# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "prep"
version = "9.0.0"
license = "MIT"
author = "John Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John Urban"
description = "Fortran pre-processor"
categories = ["preprocessing"]
keywords = ["preprocessor", "fortran", "fpm", "General Purpose Fortran" ]
homepage = "https://github.com/urbanjost"

#[library]
#source-dir="src"

[[executable]]
name="prep"
source-dir="app"
main="prep.f90"

[dependencies.M_kracken95]
git = "https://github.com/urbanjost/M_kracken95.git"

[dependencies.M_io]
git = "https://github.com/urbanjost/M_io.git"

[dependencies.M_strings]
git = "https://github.com/urbanjost/M_strings.git"

[dependencies.M_list]
git = "https://github.com/urbanjost/M_list.git"

[dependencies.M_history]
git = "https://github.com/urbanjost/M_history.git"

#rev = "92d818feb45238b1fa943a1af6186ebcbe7dc1de"
